1

   Abaqus 2024                                  Date 26-Aug-2026   Time 01:54:21
   For use by WhiteDeath under license from Dassault Systemes or its subsidiary.

 s4_train_002_long_rectangle: S4 stiffness matrix, 6-by-1 rectangle, train split 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    
 


                        S T E P       1     M A T R I X   G E N E R A T E
 
  THE FOLLOWING GLOBAL MATRICES WILL BE GENERATED AND WRITTEN TO s4_train_002_long_rectangle_X1.sim

    STIFFNESS
 
  IF MULTI-POINT CONSTRAINTS ARE SPECIFIED IN THE MODEL, THEY WILL BE APPLIED
 
  THE FOLLOWING GLOBAL MATRICES WILL BE WRITTEN TO THE FOLLOWING TEXT FILES

    STIFFNESS          TO s4_train_002_long_rectangle_STIF1.mtx
 
  MATRIX OUTPUT FORMAT - COORDINATE


          THE ANALYSIS HAS BEEN COMPLETED



     ANALYSIS SUMMARY:
     TOTAL OF          1  INCREMENTS
                       0  CUTBACKS IN AUTOMATIC INCREMENTATION
                       0  ITERATIONS INCLUDING CONTACT ITERATIONS IF PRESENT
                       0  PASSES THROUGH THE EQUATION SOLVER OF WHICH 
                       0  INVOLVE MATRIX DECOMPOSITION, INCLUDING
                       0  DECOMPOSITION(S) OF THE MASS MATRIX
                       1  REORDERING OF EQUATIONS TO MINIMIZE WAVEFRONT
                       0  ADDITIONAL RESIDUAL EVALUATIONS FOR LINE SEARCHES
                       0  ADDITIONAL OPERATOR EVALUATIONS FOR LINE SEARCHES
                       0  WARNING MESSAGES DURING USER INPUT PROCESSING
                       0  WARNING MESSAGES DURING ANALYSIS
                       0  ANALYSIS WARNINGS ARE NUMERICAL PROBLEM MESSAGES
                       0  ANALYSIS WARNINGS ARE NEGATIVE EIGENVALUE MESSAGES
                       0  ERROR MESSAGES



     JOB TIME SUMMARY
       USER TIME (SEC)      =     0.10    
       SYSTEM TIME (SEC)    =      0.0    
       TOTAL CPU TIME (SEC) =     0.10    
       WALLCLOCK TIME (SEC) =            0
       MEMORY PEAK (GB)     =            0
